# Generated by Django 4.0.2 on 2022-02-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=200)),
                ('vehicle_model', models.CharField(max_length=200)),
                ('speed', models.IntegerField()),
                ('avg_speed', models.IntegerField()),
                ('tempreture', models.IntegerField()),
                ('fuel', models.CharField(choices=[('Tank Full'), ('Tank Half'), ('Empty')], max_length=32)),
                ('engine', models.CharField(choices=[( 'Good'), ( 'Bad')], max_length=32)),
                ('power', models.CharField(choices=[( 'ON'), ('OFF')], max_length=32)),
                ('static_map', models.ImageField(upload_to='Images')),
                ('camera_one', models.CharField(choices=[('Camera 1')], max_length=32)),
                ('camera_two', models.CharField(choices=[('Camera 2')], max_length=32)),
            ],
        ),
    ]
